./main img/page-10-laboratories-hard.png dist/page-10-laboratories-hard.png xbr4x
./main img/page-10-laboratories.png dist/page-10-laboratories.png xbr4x
./main img/page-10-laboratories-soft.png dist/page-10-laboratories-soft.png xbr4x
./main img/page-11-player-buildings-hard.png dist/page-11-player-buildings-hard.png xbr4x
./main img/page-11-player-buildings.png dist/page-11-player-buildings.png xbr4x
./main img/page-11-player-buildings-soft.png dist/page-11-player-buildings-soft.png xbr4x
./main img/page-12-player-buildings.png dist/page-12-player-buildings.png xbr4x
./main img/page-13-player-buildings.png dist/page-13-player-buildings.png xbr4x
./main img/page-14-droid-hubs.png dist/page-14-droid-hubs.png xbr4x
./main img/page-15-droid-hubs.png dist/page-15-droid-hubs.png xbr4x
./main img/page-16-droid-drives.png dist/page-16-droid-drives.png xbr4x
./main img/page-17-droid-weapons.png dist/page-17-droid-weapons.png xbr4x
./main img/page-18-fx`s-hard.png dist/page-18-fx`s-hard.png xbr4x
./main img/page-18-fx`s-soft.png dist/page-18-fx`s-soft.png xbr4x
./main img/page-19-fx`s-hard.png dist/page-19-fx`s-hard.png xbr4x
./main img/page-19-fx`s-soft.png dist/page-19-fx`s-soft.png xbr4x
./main img/page-20-fx`s-hard.png dist/page-20-fx`s-hard.png xbr4x
./main img/page-20-fx`s-soft.png dist/page-20-fx`s-soft.png xbr4x
./main img/page-21-fx`s-hard.png dist/page-21-fx`s-hard.png xbr4x
./main img/page-21-fx`s-soft.png dist/page-21-fx`s-soft.png xbr4x
./main img/page-22-fx`s.png dist/page-22-fx`s.png xbr4x
./main img/page-23-fx`s-hard.png dist/page-23-fx`s-hard.png xbr4x
./main img/page-23-fx`s-soft.png dist/page-23-fx`s-soft.png xbr4x
./main img/page-24-fx`s.png dist/page-24-fx`s.png xbr4x
./main img/page-25-sky.png dist/page-25-sky.png xbr4x
./main img/page-26-sky.png dist/page-26-sky.png xbr4x
./main img/page-27-fx.png dist/page-27-fx.png xbr4x
./main img/page-6-features-arizona.png dist/page-6-features-arizona.png xbr4x
./main img/page-6-features-rockies.png dist/page-6-features-rockies.png xbr4x
./main img/page-6-features-urban-area.png dist/page-6-features-urban-area.png xbr4x
./main img/page-7-barbarians-arizona.png dist/page-7-barbarians-arizona.png xbr4x
./main img/page-7-barbarians-kevlar.png dist/page-7-barbarians-kevlar.png xbr4x
./main img/page-7-barbarians-urban.png dist/page-7-barbarians-urban.png xbr4x
./main img/page-8-player-buildings-bases.png dist/page-8-player-buildings-bases.png xbr4x
./main img/page-8-player-buildings-bases-rockies.png dist/page-8-player-buildings-bases-rockies.png xbr4x
./main img/page-8-player-buildings-bases-urban.png dist/page-8-player-buildings-bases-urban.png xbr4x
./main img/page-9-player-buildings-bases-rockies.png dist/page-9-player-buildings-bases-rockies.png xbr4x
./main img/page-9-player-buildings-bases-urban.png dist/page-9-player-buildings-bases-urban.png xbr4x
./main img/page-9-player-hard-buildings-bases.png dist/page-9-player-hard-buildings-bases.png xbr4x
./main img/page-9-player-hard-buildings-bases-rockies.png dist/page-9-player-hard-buildings-bases-rockies.png xbr4x
./main img/page-9-player-hard-buildings-bases-urban.png dist/page-9-player-hard-buildings-bases-urban.png xbr4x
./main img/page-9-player-soft-buildings-bases.png dist/page-9-player-soft-buildings-bases.png xbr4x
./main img/page-9-player-soft-buildings-bases-rockies.png dist/page-9-player-soft-buildings-bases-rockies.png xbr4x
./main img/page-9-player-soft-buildings-bases-urban.png dist/page-9-player-soft-buildings-bases-urban.png xbr4x
./main img/tertilesc1hw.png dist/tertilesc1hw.png xbr4x
./main img/tertilesc1.png dist/tertilesc1.png xbr4x
./main img/tertilesc2hw.png dist/tertilesc2hw.png xbr4x
./main img/tertilesc2.png dist/tertilesc2.png xbr4x
./main img/tertilesc3hw.png dist/tertilesc3hw.png xbr4x
./main img/tertilesc3.png dist/tertilesc3.png xbr4x